"""Auto-generate _index.md body from frontmatter.

Reads the `order`, `title`, and `description` fields from _index.md
frontmatter plus the EO files in each TO folder, and writes out the
full markdown body.  Editors only need to maintain EO files and
_index.md frontmatter — the body is regenerated by this script.

Usage:
    python scripts/generate_toc.py          # preview (dry-run)
    python scripts/generate_toc.py --write  # overwrite _index.md files
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

CONTENT_DIR = Path(__file__).resolve().parent.parent / "content"
GENERATED_MARKER = "<!-- Auto-generated by scripts/generate_toc.py — do not edit below this line -->"


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    _, fm_text, _ = text.split("---", 2)
    return yaml.safe_load(fm_text) or {}


def build_index_body(index_path: Path) -> str:
    """Return the full file content for an _index.md (frontmatter + body)."""
    fm = parse_frontmatter(index_path)
    title = fm.get("title", index_path.parent.name)
    description = fm.get("description", "")
    is_group = "group_id" in fm
    folder = index_path.parent

    # Preserve original frontmatter exactly
    raw = index_path.read_text(encoding="utf-8")
    _, fm_raw, _ = raw.split("---", 2)
    header = f"---{fm_raw}---"

    lines = [
        header,
        GENERATED_MARKER,
        "",
        f"# {title}",
        "",
        description,
        "",
    ]

    if is_group:
        # Group level: list TO subdirectories
        lines.append("## Terminal Objectives")
        lines.append("")
        to_dirs = sorted(
            [d for d in folder.iterdir() if d.is_dir() and d.name != "media"],
            key=lambda d: parse_frontmatter(d / "_index.md").get("order", 999),
        )
        for to_dir in to_dirs:
            to_index = to_dir / "_index.md"
            if to_index.exists():
                to_fm = parse_frontmatter(to_index)
                to_title = to_fm.get("title", to_dir.name)
                lines.append(f"- [{to_title}]({to_dir.name}/)")
        lines.append("")
    else:
        # TO level: list EO files sorted by order
        lines.append("## Enabling Objectives")
        lines.append("")
        eo_files = sorted(
            [f for f in folder.glob("*.md") if f.name != "_index.md"],
            key=lambda f: parse_frontmatter(f).get("order", 999),
        )
        for eo_file in eo_files:
            eo_fm = parse_frontmatter(eo_file)
            eo_title = eo_fm.get("title", eo_file.stem)
            lines.append(f"- [{eo_title}]({eo_file.name})")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate _index.md TOC from frontmatter")
    parser.add_argument("--write", action="store_true", help="Write changes to disk (default: dry-run)")
    args = parser.parse_args()

    index_files = sorted(CONTENT_DIR.rglob("_index.md"))
    changed = 0

    for index_path in index_files:
        new_content = build_index_body(index_path)
        old_content = index_path.read_text(encoding="utf-8")

        if new_content.rstrip() == old_content.rstrip():
            continue

        changed += 1
        rel = index_path.relative_to(CONTENT_DIR)

        if args.write:
            index_path.write_text(new_content, encoding="utf-8")
            print(f"  updated: {rel}")
        else:
            print(f"  would update: {rel}")

    if not changed:
        print("All _index.md files are up to date.")
    elif not args.write:
        print(f"\n{changed} file(s) would change. Run with --write to apply.")


if __name__ == "__main__":
    main()
